<?php
    include_once("db.php");
    if(!isset($_GET["id"])){
        header("location:register.php");
    }
    else{
        $code=$_GET["id"];
        if(empty($_POST["maritalstatus"]) || empty($_POST["mothertongue"]) || empty($_POST["complexion"]) || empty($_POST["birthplace"]) || empty($_POST["weight"]) || empty($_POST["height"]) || empty($_POST["bloodgroup"]) || empty($_POST["diet"]) || empty($_POST["profilecreated"]) || empty($_POST["smoke"]) || empty($_POST["drink"]) || empty($_POST["zodiac"]) || empty($_POST["education"]) || empty($_POST["income"]) || empty($_POST["fatheroccupation"]) || empty($_POST["motheroccupation"])){
            header("location:addmoredetails.php?empty=1");
        }
        else{
            $maritalstatus=$_POST["maritalstatus"];
            $mothertongue=$_POST["mothertongue"];
            $complexion=$_POST["complexion"];
            $birthplace=$_POST["birthplace"];
            $weight=$_POST["weight"];
            $height=$_POST["height"];
            $bloodgroup=$_POST["bloodgroup"];
            $diet=$_POST["diet"];
            $profilecreated=$_POST["profilecreated"];
            $smoke=$_POST["smoke"];
            $drink=$_POST["drink"];
            $zodiac=$_POST["zodiac"];
            $education=$_POST["education"];
            $income=$_POST["income"];
            $fatheroccupation=$_POST["fatheroccupation"];
            $motheroccupation=$_POST["motheroccupation"];
            if(mysqli_query($conn,"insert into moredetails values('$code','$maritalstatus','$mothertongue','$complexion','$birthplace','$weight','$height','$bloodgroup','$diet','$profilecreated','$smoke','$drink','$zodiac','$education','$income','$fatheroccupation','$motheroccupation')")>0){
                header("location:login.php?success=1");
            }
            else{
                header("location:addmoredetails.php?id=".$code);
            }
        }
    }
?>